dateModified: 1639587583
email:
  fromEmail: ted.flynn@hey.com
  fromName: Vite-O-Rama
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    1acca259-1a15-45ba-ae23-378f2bf9bb3f: Vite-O-Rama # Vite-O-Rama
    018d2303-6ebc-4d18-89b4-69c5c4711d99: Vite-O-Rama # Vite-O-Rama
    fefc2507-5a34-43ee-b9ca-9e3fee865033: Common # Common
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: Vite-O-Rama
  schemaVersion: 3.7.8
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
